# Generated by Django 4.0.4 on 2022-06-01 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All_Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stock_name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=100)),
                ('quantity', models.IntegerField(default='1')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('transaction_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_unit', models.IntegerField()),
                ('total_investment', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Sold_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Current_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Over_all_profit', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='User_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=100)),
                ('quantity', models.IntegerField(default='1')),
                ('transaction_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('transaction_date', models.DateTimeField()),
                ('choose_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.all_stock')),
            ],
        ),
    ]
