# Generated by Django 4.0.4 on 2022-06-01 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual_Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stock.all_stock')),
            ],
        ),
    ]
