# Generated by Django 4.0.4 on 2022-06-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0002_individual_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_stock',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
